### PR TITLE
fix: append layout preview css to iframe head

### LINKED ISSUE #687: CSS coming from layout is not applied on preview
The current `<NewsletterPreview />` adds an inline `<style />` tag to apply the layout styles to the preview. This no longer works on WordPress 5.9 because previews are now [iframed editors](https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/) and don't inherit these styles.

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR implements the required hooks to apply a newsletter layout custom CSS to the Post Inserter block previews. It fixes the display for layout preview and newsletter editing.

Closes #687 

### How to test the changes in this Pull Request:

1. Make sure you have WordPress 5.9 RC 2 installed
2. While on the master branch, create a newsletter layout with custom fonts and a Posts Inserter block
3. Click to create a new newsletter, choose the created layout and observe the Posts Inserter block does not apply the selected fonts
4. Check out this branch, run `npm run build` and refresh the page
5. Observe the fonts are now applied
6. Select the layout to enter the newsletter editor and observe the fonts are also applied
7. Repeat the steps above in WordPress 5.8 to make sure there are no regressions

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: src/editor/blocks/posts-inserter/posts-preview.js [hunk 1]
```diff
@@ -12,25 +12,51 @@ import { forwardRef } from '@wordpress/element';
...
 	// Iframe styles are not properly applied when nesting iframed editors.
 	// This fix ensures the iframe is properly styled.
-	const fixIframe = useRefEffect( node => {
+	const useIframeBorderFix = useRefEffect( node => {
 		const updateIframeStyle = () => {
 			const iframe = node.querySelector( 'iframe[title="Editor canvas"]' );
 			if ( iframe ) {
-				iframe.style.border = 0;
-				observer.disconnect();
+				iframe.addEventListener( 'load', () => {
```
Comment (dkoo) [inline src/editor/blocks/posts-inserter/posts-preview.js:19]: Causes issues for me in Chrome. This event listener never seems to fire.

File: src/editor/blocks/posts-inserter/posts-preview.js [hunk 2]
```diff
@@ -12,25 +12,51 @@ import { forwardRef } from '@wordpress/element';
...
+	// Append layout style if viewing layout preview.
+	const useLayoutStyle = useRefEffect( node => {
+		const style = document.getElementById( 'newspack-newsletters__layout-css' );
+		if ( ! style ) {
+			return;
+		}
+		const appendLayoutStyle = () => {
+			const iframe = node.querySelector( 'iframe[title="Editor canvas"]' );
+			if ( iframe ) {
+				iframe.addEventListener( 'load', () => {
```
Comment (dkoo) [inline src/editor/blocks/posts-inserter/posts-preview.js:41]: May need to run this without an event listener too.

**Review by dkoo — CHANGES_REQUESTED** [review]
As discussed with @miguelpeixe, I'm seeing a regression with the iframe borders coming back inside the preview windows in Chrome only. I think this is related to wonkiness with the `load` event listener, which is apparently required for fixing preview styles in Firefox, so we may need two handlers here

The custom font fix looks 👍 in Chrome but not Firefox (which is pending a [core fix](https://github.com/WordPress/gutenberg/pull/38049)).

**Comment by miguelpeixe** [comment]
a2f6afbd399258f599d1b7d5a8504e37da8210be ensures the iframe styles are applied by calling it on both occasions. Note that the `appendChild()` now verifies if the style hasn't yet been appended.

**Review by dkoo — APPROVED** [review]
a2f6afb fixes the issue in Chrome with the border styles not being applied. Thanks for the update!
