### PR TITLE
Fix/iframed previews

### LINKED ISSUE #683: Post Inserter displaying controls on layout preview
The Posts Inserter block should display the preview of posts on layout preview.

| Expected (WP 5.8) | Actual (WP 5.9 RC2) |
| - | - |
| image | image |

### LINKED ISSUE #684: Glitchy scrollbar on layout preview
https://user-images.githubusercontent.com/820752/149557952-a6567471-7d00-4cce-ae88-ee1d5835355c.mov

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

A few fixes for bugs that were introduced by WordPress 5.9.

 - f5e56f6a6f1d2928108d828ce02322b38d41263d closes #684 
 - e2208a5fafb50b1c6cd164f9efa719a61fced868 ensures the default button positioning applied to all other default layouts
 - 7d139097634913a2c8542c72607921c6611ce7de closes #683 
 - 4a0818c8f2c877a900957fa8f26c9405638134c0 fixes nested iframe styles. The new iframed editor does not apply common styles when nested (iframed layout preview -> iframed posts preview). The change proposed in this commit ensure the iframe border style:

| Before | After |
| - | - |
| image | image |

Note that these changes will not work on Firefox due to https://github.com/WordPress/gutenberg/issues/37961

### How to test the changes in this Pull Request:

The bugs listed above should be fixed (in Chrome and Safari) and the layout and Post Inserter previews should continue to work as expected in 5.8.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: src/editor/blocks/posts-inserter/posts-preview.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+ * Posts Preview component.
+ */
+const PostsPreview = ( { isReady, blocks, viewportWidth }, ref ) => {
+	// Iframe styles are not properly applied when nesting iframed editors.
+	// This fix ensures the iframe is properly styled.
+	const fixIframe = useRefEffect( node => {
+		const updateIframeStyle = () => {
+			const iframe = node.querySelector( 'iframe[title="Editor canvas"]' );
+			if ( iframe ) {
+				iframe.style.border = 0;
```
Comment (dkoo) [inline src/editor/blocks/posts-inserter/posts-preview.js:19]: Not sure if the following would be needed, but this would be a good opportunity to pass a style object as a prop so we can apply any arbitrary styles as needed.

**Review by dkoo — APPROVED** [review]
Works as described! It also does partially fix the display in FF for me, at least by removing the border from the nested `iframe`.

**Comment by dkoo** [comment]
Also tested in WP 5.8 and didn't see any regressions there.

File: src/editor/blocks/posts-inserter/posts-preview.js (hunk 1 above)
Comment (miguelpeixe) [reply src/editor/blocks/posts-inserter/posts-preview.js:19]: I'm not sure we want arbitrary styles being applied to the iframe element itself. This is more of a normalizer effect for bugfixing than a feature. The `<div />` containing the preview should be able to handle customizations.

I also assume that nested editor iframes lacking styles is a Gutenberg bug that should be resolved at some point and we will no longer need this effect.

**Comment by miguelpeixe** [comment]
Thank you for revising, @dkoo!
