### PR TITLE
fix: only add newsletters to categories and tags archives queries

### LINKED ISSUE #637: Breaking WooCommerce Product Category Pages
WooCommerce product category is not showing any products.  The catalog visibility is set to catalog and search and products are in stock.  Mississippi Today first reported it, and part of my troubleshooting led me to look at other sites.  So I checked Plainsman Herald, The Pavlovic Today, and Grice Connect and all of them are experiencing the same result.

I spun up a clone site and disabled all plugins 1-by-1.  Found that Newsletters was causing the issue.  Reproduced it on the live site by only disabling Newsletters and got the same result.

Related: https://a8c.slack.com/archives/C01C378QWRX/p1638476150117800

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Ensure the hook to display newsletters in archives only applies to the archives it belongs (categories and tags).

The overwrite of empty `post_type` can mess with how custom taxonomies and custom post types interact.

Closes #637

### How to test the changes in this Pull Request:

Make sure #637 is no longer reproducible and public newsletters are still shown in categories/tags archives.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: includes/class-newspack-newsletters.php [hunk 1]
```diff
@@ -1208,7 +1208,7 @@ public static function display_newsletters_in_archives( $query ) {
 		if ( is_admin() || ! $query->is_main_query() ) {
 			return;
 		}
-		if ( $query->is_archive() && ! $query->is_post_type_archive() ) {
+		if ( ( $query->is_tag() || $query->is_category() ) && $query->is_archive() ) {
```
Comment (leogermani) [inline includes/class-newspack-newsletters.php:1211]: is_tag and is_category are always archives... isn't the last check redundant?

Comment (miguelpeixe) [reply includes/class-newspack-newsletters.php]: You're right! Fixed in f4871e6792380c89b2a1f30bdb0ee71f01a1d3ed
